name: Azure-Powershell-Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run PowerShell Script
      run: |
        pwsh -File ./CreateVM.ps1
